faq/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'faq'
urlpatterns = [
    path('', views.home, name='home'),
    path('<int:answer_id>/', views.detail, name='detail'),
]

faq/models.py
from django.db import models
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify

class Answer(models.Model):
    title = models.CharField(max_length=500)
    text = MarkdownxField()
    #text = models.TextField()
    photo = models.FileField(blank=True)
    attach = models.FileField(blank=True)
    is_display = models.BooleanField(default=0)
    view_cnt = models.PositiveIntegerField(default=0)
    create_date = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    # Create a property that returns the markdown instead
    @property
    def formatted_markdown(self):
        return markdownify(self.text)

faq/views.py
from django.shortcuts import render
from .models import Answer

def home(request):
    latest_answer_list = Answer.objects.filter(is_display__exact=1).order_by('-create_date')[:6]
    context = { 'latest_answer_list':latest_answer_list }
    return render(request, 'home.html', context)

def detail(request, answer_id):
    try:
        answer = Answer.objects.get(pk=answer_id)
    except QueAnswerstion.DoesNotExist:
        raise Http404("Answer does not exist")
    context = { 'answer':answer }
    return render(request, 'detail.html', context)

faq/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/faq.css' %}">
    <script src="{% static 'js/faq.js' %}"></script>
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'faq:home' %}">Global e-Campus Helpdesk</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'faq:home' %}">첫화면
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'chat:room' %}">채팅</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/mon/">모니터링</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="modal" data-target="#fordevelop">개발일지</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="mailto:kkoon79@gmail.com">문의</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
      
    <!-- Page Content -->
    <div class="container">
{% block content %}
{% endblock %}
    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">COPYRIGHT &copy; 2018 HYUNDAI AUTOEVER CORP. ALL RIGHTS RESERVED.</p>
      </div>
      <!-- /.container -->
    </footer>


    <!-- Modal -->
    <div class="modal fade" id="oops" tabindex="-1" role="dialog" aria-labelledby="oops" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <!-- <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">안내문</h5>
          </div> -->
          <div class="modal-body">
            준비중입니다.
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fas fa-times"></i> 닫기</button>
          </div>
        </div>
      </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="fordevelop" tabindex="-1" role="dialog" aria-labelledby="fordevelop" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-body">
            개발 매뉴얼로 이동하시겠습니까?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal" id="btn_manual"><i class="fas fa-arrow-alt-circle-right"></i> 이동</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fas fa-times"></i> 닫기</button>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

faq/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if answer %}
<!-- Page Heading -->
<!-- Header - set the background image for the header in the line below -->
<header class="py-5 bg-image-full" style="background-image: url('{% if answer.photo %}{{ answer.photo.url }}{% else %}{% static 'images/no-image.png' %}{% endif %}');">
  <h1 class="my-4 detail_header">{{ answer.title }}</h1>
</header>
    
<div class="py-5">
  <div>{{ answer.formatted_markdown|safe }}</div>
  {% if answer.attach %}
    <hr>
    <div class="detail_download"># 첨부파일: <i class="fas fa-download"></i> <a href="{{ answer.attach.url }}">{{ answer.attach.name }} </a></div>
  {% endif %}
  <hr>
  <div class="text-center"><button class="btn btn-primary" id="btn_back"><i class="fas fa-undo"></i> 되돌아가기</button></div>
</div>
{% else %}
<p>No answer.</p>
{% endif %}
{% endblock %}

faq/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Page Heading -->
<h1 class="my-4">Recently Answers</h1>

{% if latest_answer_list %}
<div class="row">
  {% for ans in latest_answer_list %}
  <div class="col-lg-4 col-sm-6 portfolio-item">
    <div class="card d-block">
      <a href="{% url 'faq:detail' answer_id=ans.id %}"><img class="card-img-top" src="{% if ans.photo %}{{ ans.photo.url }}{% else %}{% static 'images/no-image.png' %}{% endif %}" alt=""></a>
      <div class="card-body">
        <h4 class="card-title">
          <a href="/{{ ans.id }}">{{ ans.title }}</a>
        </h4>
        <p class="card-text">{{ ans.formatted_markdown|safe|striptags|truncatechars:200 }}</p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<!-- /.row -->
<!-- Pagination -->
<!--
<ul class="pagination justify-content-center">
  <li class="page-item">
    <a class="page-link" aria-label="Previous">
      <span aria-hidden="true">&laquo;</span>
      <span class="sr-only">Previous</span>
    </a>
  </li>
  <li class="page-item">
    <a class="page-link">1</a>
  </li>
  <li class="page-item">
    <a class="page-link">2</a>
  </li>
  <li class="page-item">
    <a class="page-link">3</a>
  </li>
  <li class="page-item">
    <a class="page-link" aria-label="Next">
      <span aria-hidden="true">&raquo;</span>
      <span class="sr-only">Next</span>
    </a>
  </li>
</ul>
-->
{% else %}
    <p>등록된 FAQ가 없습니다.</p>
{% endif %}
{% endblock %}